import Footer from './components/Footer'
import Navbar from './components/Navbar'
import Providers from './components/providers/providers'
import FloatingAction from './components/theme/FloatingAction'
import './globals.css'
import StyledComponentsRegistry from '@/lib/AntdRegistry'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gab dev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className='dark:bg-slate-900'>
        <Providers>
      <StyledComponentsRegistry>
        <Navbar/>
        {children}
        <Footer/>
        <FloatingAction />
        </StyledComponentsRegistry>
        </Providers>
        </body>
    </html>
  )
}
