import Footer from './components/Footer'
import Navbar from './components/Navbar'
import FloatingAction from './components/theme/FloatingAction'
import './globals.css'
import StyledComponentsRegistry from '@/lib/AntdRegistry'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Gab dev',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <StyledComponentsRegistry>
        <Navbar/>
        {children}
        <Footer/>
        <FloatingAction />
        </StyledComponentsRegistry>
        </body>
    </html>
  )
}
